// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/accounts": {
            "post": {
                "description": "Registers a new user in the database and returns the created ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Create Account",
                "parameters": [
                    {
                        "description": "Account data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_antonioducs_wyd_web-api_internal_api_dto.CreateAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_antonioducs_wyd_web-api_internal_api_dto.CreateAccountResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_antonioducs_wyd_web-api_internal_api_dto.CreateAccountRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "antonio@wyd.com"
                },
                "password": {
                    "type": "string",
                    "example": "senha_super_secreta"
                },
                "username": {
                    "type": "string",
                    "minLength": 3,
                    "example": "antonio_hero"
                }
            }
        },
        "github_com_antonioducs_wyd_web-api_internal_api_dto.CreateAccountResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 105
                },
                "username": {
                    "type": "string",
                    "example": "antonio_hero"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Open WYD Web API",
	Description:      "API for managing accounts and characters of the Open WYD server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
