// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkg/proto/gateway/gateway.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_DATA       EventType = 0
	EventType_CONNECT    EventType = 1
	EventType_DISCONNECT EventType = 2
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "DATA",
		1: "CONNECT",
		2: "DISCONNECT",
	}
	EventType_value = map[string]int32{
		"DATA":       0,
		"CONNECT":    1,
		"DISCONNECT": 2,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_gateway_gateway_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_pkg_proto_gateway_gateway_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_gateway_proto_rawDescGZIP(), []int{0}
}

type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     uint32                 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Type          EventType              `protobuf:"varint,2,opt,name=type,proto3,enum=gateway.EventType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_pkg_proto_gateway_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *Packet) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_DATA
}

func (x *Packet) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_pkg_proto_gateway_gateway_proto protoreflect.FileDescriptor

const file_pkg_proto_gateway_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/proto/gateway/gateway.proto\x12\agateway\"i\n" +
	"\x06Packet\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\rR\tsessionId\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.gateway.EventTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload*2\n" +
	"\tEventType\x12\b\n" +
	"\x04DATA\x10\x00\x12\v\n" +
	"\aCONNECT\x10\x01\x12\x0e\n" +
	"\n" +
	"DISCONNECT\x10\x022A\n" +
	"\bGameGate\x125\n" +
	"\rStreamPackets\x12\x0f.gateway.Packet\x1a\x0f.gateway.Packet(\x010\x01B.Z,github.com/antonioducs/wyd/pkg/proto/gatewayb\x06proto3"

var (
	file_pkg_proto_gateway_gateway_proto_rawDescOnce sync.Once
	file_pkg_proto_gateway_gateway_proto_rawDescData []byte
)

func file_pkg_proto_gateway_gateway_proto_rawDescGZIP() []byte {
	file_pkg_proto_gateway_gateway_proto_rawDescOnce.Do(func() {
		file_pkg_proto_gateway_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_gateway_gateway_proto_rawDesc), len(file_pkg_proto_gateway_gateway_proto_rawDesc)))
	})
	return file_pkg_proto_gateway_gateway_proto_rawDescData
}

var file_pkg_proto_gateway_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_gateway_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_gateway_gateway_proto_goTypes = []any{
	(EventType)(0), // 0: gateway.EventType
	(*Packet)(nil), // 1: gateway.Packet
}
var file_pkg_proto_gateway_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.Packet.type:type_name -> gateway.EventType
	1, // 1: gateway.GameGate.StreamPackets:input_type -> gateway.Packet
	1, // 2: gateway.GameGate.StreamPackets:output_type -> gateway.Packet
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_gateway_gateway_proto_init() }
func file_pkg_proto_gateway_gateway_proto_init() {
	if File_pkg_proto_gateway_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_gateway_gateway_proto_rawDesc), len(file_pkg_proto_gateway_gateway_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_gateway_gateway_proto_goTypes,
		DependencyIndexes: file_pkg_proto_gateway_gateway_proto_depIdxs,
		EnumInfos:         file_pkg_proto_gateway_gateway_proto_enumTypes,
		MessageInfos:      file_pkg_proto_gateway_gateway_proto_msgTypes,
	}.Build()
	File_pkg_proto_gateway_gateway_proto = out.File
	file_pkg_proto_gateway_gateway_proto_goTypes = nil
	file_pkg_proto_gateway_gateway_proto_depIdxs = nil
}
