// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: pkg/proto/gateway/gateway.proto

package gateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameGate_StreamPackets_FullMethodName = "/gateway.GameGate/StreamPackets"
)

// GameGateClient is the client API for GameGate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameGateClient interface {
	StreamPackets(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Packet, Packet], error)
}

type gameGateClient struct {
	cc grpc.ClientConnInterface
}

func NewGameGateClient(cc grpc.ClientConnInterface) GameGateClient {
	return &gameGateClient{cc}
}

func (c *gameGateClient) StreamPackets(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Packet, Packet], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GameGate_ServiceDesc.Streams[0], GameGate_StreamPackets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Packet, Packet]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameGate_StreamPacketsClient = grpc.BidiStreamingClient[Packet, Packet]

// GameGateServer is the server API for GameGate service.
// All implementations must embed UnimplementedGameGateServer
// for forward compatibility.
type GameGateServer interface {
	StreamPackets(grpc.BidiStreamingServer[Packet, Packet]) error
	mustEmbedUnimplementedGameGateServer()
}

// UnimplementedGameGateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameGateServer struct{}

func (UnimplementedGameGateServer) StreamPackets(grpc.BidiStreamingServer[Packet, Packet]) error {
	return status.Error(codes.Unimplemented, "method StreamPackets not implemented")
}
func (UnimplementedGameGateServer) mustEmbedUnimplementedGameGateServer() {}
func (UnimplementedGameGateServer) testEmbeddedByValue()                  {}

// UnsafeGameGateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameGateServer will
// result in compilation errors.
type UnsafeGameGateServer interface {
	mustEmbedUnimplementedGameGateServer()
}

func RegisterGameGateServer(s grpc.ServiceRegistrar, srv GameGateServer) {
	// If the following call panics, it indicates UnimplementedGameGateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameGate_ServiceDesc, srv)
}

func _GameGate_StreamPackets_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameGateServer).StreamPackets(&grpc.GenericServerStream[Packet, Packet]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameGate_StreamPacketsServer = grpc.BidiStreamingServer[Packet, Packet]

// GameGate_ServiceDesc is the grpc.ServiceDesc for GameGate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameGate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.GameGate",
	HandlerType: (*GameGateServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPackets",
			Handler:       _GameGate_StreamPackets_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/gateway/gateway.proto",
}
