// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: characters.sql

package db

import (
	"context"
)

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (
    account_id,
    name,
    level,
    experience,
    gold,
    guild_id,
    pos_x,
    pos_y,
    slot,
    class_id,
    status,
    equipment,
    inventory
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, account_id, name, level, experience, gold, guild_id, pos_x, pos_y, slot, class_id, status, equipment, inventory, created_at, updated_at
`

type CreateCharacterParams struct {
	AccountID  int32  `json:"account_id"`
	Name       string `json:"name"`
	Level      int32  `json:"level"`
	Experience int64  `json:"experience"`
	Gold       int32  `json:"gold"`
	GuildID    int32  `json:"guild_id"`
	PosX       int32  `json:"pos_x"`
	PosY       int32  `json:"pos_y"`
	Slot       int32  `json:"slot"`
	ClassID    int32  `json:"class_id"`
	Status     []byte `json:"status"`
	Equipment  []byte `json:"equipment"`
	Inventory  []byte `json:"inventory"`
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, createCharacter,
		arg.AccountID,
		arg.Name,
		arg.Level,
		arg.Experience,
		arg.Gold,
		arg.GuildID,
		arg.PosX,
		arg.PosY,
		arg.Slot,
		arg.ClassID,
		arg.Status,
		arg.Equipment,
		arg.Inventory,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Level,
		&i.Experience,
		&i.Gold,
		&i.GuildID,
		&i.PosX,
		&i.PosY,
		&i.Slot,
		&i.ClassID,
		&i.Status,
		&i.Equipment,
		&i.Inventory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCharacter = `-- name: DeleteCharacter :exec
DELETE FROM characters
WHERE id = $1
`

func (q *Queries) DeleteCharacter(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCharacter, id)
	return err
}

const getCharacterByID = `-- name: GetCharacterByID :one
SELECT id, account_id, name, level, experience, gold, guild_id, pos_x, pos_y, slot, class_id, status, equipment, inventory, created_at, updated_at
FROM characters
WHERE id = $1
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetCharacterByID(ctx context.Context, id int32) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacterByID, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Level,
		&i.Experience,
		&i.Gold,
		&i.GuildID,
		&i.PosX,
		&i.PosY,
		&i.Slot,
		&i.ClassID,
		&i.Status,
		&i.Equipment,
		&i.Inventory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCharacterByName = `-- name: GetCharacterByName :one
SELECT id, account_id, name, level, experience, gold, guild_id, pos_x, pos_y, slot, class_id, status, equipment, inventory, created_at, updated_at
FROM characters
WHERE name = $1
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetCharacterByName(ctx context.Context, name string) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacterByName, name)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Level,
		&i.Experience,
		&i.Gold,
		&i.GuildID,
		&i.PosX,
		&i.PosY,
		&i.Slot,
		&i.ClassID,
		&i.Status,
		&i.Equipment,
		&i.Inventory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCharactersByAccountID = `-- name: GetCharactersByAccountID :many
SELECT id, account_id, name, level, experience, gold, guild_id, pos_x, pos_y, slot, class_id, status, equipment, inventory, created_at, updated_at
FROM characters
WHERE account_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetCharactersByAccountID(ctx context.Context, accountID int32) ([]Character, error) {
	rows, err := q.db.Query(ctx, getCharactersByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Level,
			&i.Experience,
			&i.Gold,
			&i.GuildID,
			&i.PosX,
			&i.PosY,
			&i.Slot,
			&i.ClassID,
			&i.Status,
			&i.Equipment,
			&i.Inventory,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCharacter = `-- name: UpdateCharacter :exec
UPDATE characters
SET
    name = $2,
    level = $3,
    experience = $4,
    gold = $5,
    guild_id = $6,
    pos_x = $7,
    pos_y = $8,
    status = $9,
    equipment = $10,
    inventory = $11,
    updated_at = NOW()
WHERE id = $1
`

type UpdateCharacterParams struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	Level      int32  `json:"level"`
	Experience int64  `json:"experience"`
	Gold       int32  `json:"gold"`
	GuildID    int32  `json:"guild_id"`
	PosX       int32  `json:"pos_x"`
	PosY       int32  `json:"pos_y"`
	Status     []byte `json:"status"`
	Equipment  []byte `json:"equipment"`
	Inventory  []byte `json:"inventory"`
}

func (q *Queries) UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) error {
	_, err := q.db.Exec(ctx, updateCharacter,
		arg.ID,
		arg.Name,
		arg.Level,
		arg.Experience,
		arg.Gold,
		arg.GuildID,
		arg.PosX,
		arg.PosY,
		arg.Status,
		arg.Equipment,
		arg.Inventory,
	)
	return err
}
